### ISSUE TITLE
Error en laptop 32 bits

### ISSUE THREAD

**Issue by SonicFanCreations** [MDCYT/MDC-Engine#3]
Buenas,vengo a reportar un error en su custom week.
![image](https://user-images.githubusercontent.com/89678995/131208079-6b65a920-ccb8-4bbf-b3aa-df8637138453.png)
como puede ver en la imagen eso es lo que me sale cuando intento abrir el .exe del funkin
yo en esta laptop tengo windows 8 con 32 bits y me sale eso...
porfavor arreglendo porque me gustaria mucho trabajar en mi mod
**-SonicFanCreations**
PD:
_no he editado nada en el juego,asi esta por defecto_

**Comment by MDCYT** [comment]
Hola, en cuando llegue a mi casa, se hará revisión del tema, gracias por reportar el fallo.

**Comment by JB985** [comment]
y yo pensaba que era el unico que le ocurria el error

**Comment by galleniz** [comment]
> Hola, en cuando llegue a mi casa, se hará revisión del tema, gracias por reportar el fallo.

¿Nunca llegaste?

Sobre el error: El motor está compilado en 64 bits, la solución es compilarlo en 64 bits.

**Comment by MDCYT** [comment]
> > Hola, en cuando llegue a mi casa, se hará revisión del tema, gracias por reportar el fallo.
> 
> ¿Nunca llegaste?
> 
> Sobre el error: El motor está compilado en 64 bits, la solución es compilarlo en 64 bits.

Si, nunca llegue, LoL
